list: $/pensoft/contactform/models/data/columns.yaml
modelClass: Pensoft\ContactForm\Models\Data
title: Mails
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/contactform/mails/update/:id'
